### ISSUE TITLE
Unhandled python exception in read callback: AttributeError: 'Popen' object has no attribute 'cmd'

### ISSUE THREAD

**Issue by rgynn** [deniszh/collectd-iostat-python#10]
Started getting these errors from a week ago. Any idea why?

Python 2.6.6
CentOS release 6.8 (Final)

[2016-09-16 12:03:50] Unhandled python exception in read callback: AttributeError: 'Popen' object has no attribute 'cmd'
[2016-09-16 12:03:50] Traceback (most recent call last):
[2016-09-16 12:03:50]   File "/usr/lib64/collectd/collectd-iostat/collectd_iostat_python.py", line 276, in read_callback
    ds = iostat.get_diskstats()
[2016-09-16 12:03:50]   File "/usr/lib64/collectd/collectd-iostat/collectd_iostat_python.py", line 142, in get_diskstats
    dsd = self._get_childs_data(dstats)
[2016-09-16 12:03:50]   File "/usr/lib64/collectd/collectd-iostat/collectd_iostat_python.py", line 132, in _get_childs_data
    raise CmdError('Command %r returned %d' % (child.cmd, ecode))
[2016-09-16 12:03:50] AttributeError: 'Popen' object has no attribute 'cmd'
[2016-09-16 12:03:50] read-function of plugin `python.collectd_iostat_python' failed. Will suspend it for 64.000 seconds.

**Comment by rgynn** [comment]
noticed sysstat package wasn't present on new installation. Ticket closed.
